export const ErrorCodes = {
    FILE_TOO_LARGE: 'FILE_TOO_LARGE',
    INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
    TASK_NOT_FOUND: 'TASK_NOT_FOUND',
    TASK_FAILED: 'TASK_FAILED',
    UNAUTHORIZED: 'UNAUTHORIZED',
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
};
//# sourceMappingURL=error-codes.js.map